# Generated by Django 3.0.5 on 2020-05-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(choices=[('71-80', '71-80'), ('71-80', '81-90'), ('71-80', '91-100'), ('71-100', '71-100'), ('131-140', '101-110'), ('141-150', '111-120'), ('151-160', '121-130'), ('101-130', '101-130'), ('131-140', '131-140'), ('141-150', '141-150'), ('151-160', '151-160'), ('131-160', '131-160')], max_length=7, null=True)),
                ('level', models.CharField(choices=[('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3')], max_length=7, null=True)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Challenge')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Course')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Skill')),
                ('skill_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Skillcategory')),
            ],
        ),
    ]
