# Generated by Django 3.0.5 on 2020-05-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Testcreation')),
            ],
        ),
        migrations.CreateModel(
            name='Testinputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footwork', models.BooleanField()),
                ('middle', models.BooleanField()),
                ('bat_position', models.BooleanField()),
                ('head_position', models.BooleanField()),
                ('elbow_position', models.BooleanField()),
                ('shoulder_line', models.BooleanField()),
                ('ball_direction', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
    ]
