# Generated by Django 3.0.5 on 2020-05-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tests', '0002_test_testinputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='ball_direction',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='bat_position',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='elbow_position',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='footwork',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='head_position',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='middle',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='shoulder_line',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='Testinputs',
        ),
    ]
