# Generated by Django 3.0.5 on 2020-05-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
        ('tests', '0004_auto_20200505_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ball_direction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='bat_position',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='elbow_position',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='footwork',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='head_position',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='middle',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='shoulder_line',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcreation',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Challenge'),
        ),
        migrations.AlterField(
            model_name='testcreation',
            name='level',
            field=models.CharField(blank=True, choices=[('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='testcreation',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Skill'),
        ),
        migrations.AlterField(
            model_name='testcreation',
            name='skill_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Skillcategory'),
        ),
        migrations.AlterField(
            model_name='testcreation',
            name='speed',
            field=models.CharField(blank=True, choices=[('71-80', '71-80'), ('71-80', '81-90'), ('71-80', '91-100'), ('71-100', '71-100'), ('131-140', '101-110'), ('141-150', '111-120'), ('151-160', '121-130'), ('101-130', '101-130'), ('131-140', '131-140'), ('141-150', '141-150'), ('151-160', '151-160'), ('131-160', '131-160')], max_length=7, null=True),
        ),
    ]
