# Generated by Django 3.0.5 on 2020-05-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20200505_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='ball_direction',
        ),
        migrations.RemoveField(
            model_name='test',
            name='bat_position',
        ),
        migrations.RemoveField(
            model_name='test',
            name='elbow_position',
        ),
        migrations.RemoveField(
            model_name='test',
            name='footwork',
        ),
        migrations.RemoveField(
            model_name='test',
            name='head_position',
        ),
        migrations.RemoveField(
            model_name='test',
            name='middle',
        ),
        migrations.RemoveField(
            model_name='test',
            name='shoulder_line',
        ),
        migrations.CreateModel(
            name='Testinputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_count', models.PositiveSmallIntegerField()),
                ('footwork', models.BooleanField(blank=True, null=True)),
                ('middle', models.BooleanField(blank=True, null=True)),
                ('bat_position', models.BooleanField(blank=True, null=True)),
                ('head_position', models.BooleanField(blank=True, null=True)),
                ('elbow_position', models.BooleanField(blank=True, null=True)),
                ('shoulder_line', models.BooleanField(blank=True, null=True)),
                ('ball_direction', models.BooleanField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
        ),
    ]
